language: cpp
matrix:
  include:
    - os: osx
      compiler: clang
      addons:
        homebrew:
          packages:
            yasm
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            yasm

script:
  ./build.sh
