language: cpp
matrix:
  include:
    - os: osx
      compiler: clang
      addons:
        homebrew:
          packages:
            yasm
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            yasm
    # Once Travis' Windows support gets fleshed out, use addons and other niceties.
    - os: windows
      install: choco install yasm

script:
  ./build.sh
